// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB09snKXh3M1s3ngWnEm0PP9THEuzkXB_Q',
    appId: '1:147666423501:web:f2de49f1245d2b810ae384',
    messagingSenderId: '147666423501',
    projectId: 'dashboard-scanner',
    authDomain: 'dashboard-scanner.firebaseapp.com',
    storageBucket: 'dashboard-scanner.firebasestorage.app',
    measurementId: 'G-F4P5Z1JLP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNiNnFa1-reIYiFkIqYgJrmGULLwNvdQQ',
    appId: '1:147666423501:android:87a6317345beac550ae384',
    messagingSenderId: '147666423501',
    projectId: 'dashboard-scanner',
    storageBucket: 'dashboard-scanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeW2EmzXN-0UQbRB-5iPIifsOyRmMSwug',
    appId: '1:147666423501:ios:bd993abe6b475cc00ae384',
    messagingSenderId: '147666423501',
    projectId: 'dashboard-scanner',
    storageBucket: 'dashboard-scanner.firebasestorage.app',
    iosBundleId: 'com.example.warninglightScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeW2EmzXN-0UQbRB-5iPIifsOyRmMSwug',
    appId: '1:147666423501:ios:bd993abe6b475cc00ae384',
    messagingSenderId: '147666423501',
    projectId: 'dashboard-scanner',
    storageBucket: 'dashboard-scanner.firebasestorage.app',
    iosBundleId: 'com.example.warninglightScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB09snKXh3M1s3ngWnEm0PP9THEuzkXB_Q',
    appId: '1:147666423501:web:2616bf0143b7a39d0ae384',
    messagingSenderId: '147666423501',
    projectId: 'dashboard-scanner',
    authDomain: 'dashboard-scanner.firebaseapp.com',
    storageBucket: 'dashboard-scanner.firebasestorage.app',
    measurementId: 'G-JBT8E6Q4LN',
  );
}
